version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    labels:
      - area/dependencies
    schedule:
      interval: daily

  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"