# Copyright (c) 2025 Kevin Berger <huhouhuam@gmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file.

# This file contains all available configuration options
# with their default values.

# Options for analysis running
version: "2"
run:
  modules-download-mode: readonly
  concurrency: 4
  timeout: 10m
  issues-exit-code: 1
  tests: true

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: disable

linters:
  enable:
    - asciicheck
    - dogsled
    - errorlint
    - copyloopvar
    - goconst
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace
  disable:
    - errcheck
  settings:
    errcheck:
      check-blank: false
      exclude-functions:
        - fmt:.*
    nolintlint:
      allow-unused: true
      require-specific: true
    revive:
      rules:
        - name: package-comments
          disabled: true
  exclusions:
    paths:
      - "e2e"
      - "examples"
      - "creation"
issues:
  # Maximum issues count per one linter (set to 0 to disable)
  max-issues-per-linter: 0

  # Maximum count of issues with the same text (set to 0 to disable)
  max-same-issues: 0