#!/usr/bin/env bash

# Copyright (c) 2025 Kevin Berger <huhouhuam@gmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file.

# Store this file as .git/hooks/commit-msg in your repository in order to
# enforce checking for proper commit message format before actual commits. You
# may need to make the script executable by 'chmod +x .git/hooks/commit-msg'.

# commit-msg use go-gitlint tool, install go-gitlint via `go get github.com/huhouhua/go-gitlint/cmd/go-gitlint`

if [[ -x "$(command -v go-gitlint)" ]]
then
    go-gitlint --msg-file="$1"
elif [[ -f "$(go env GOPATH)/bin/go-gitlint" ]]
then
    $(go env GOPATH)/bin/go-gitlint --msg-file="$1"
else
    echo "Error: go-gitlint not found, Please execute (make install.go-gitlint)"
    exit 1