name: lint and Test

on: [push, pull_request]

jobs:
  lint_and_test:
    name: Lint and Test - ${{ matrix.go-version }}
    strategy:
      matrix:
        go-version: [1.24.x, 1.23.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: false

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          make tools

      - name: Check copyright
        run: |
          make verify-copyright

#      - name: Check syntax and styling of go sources
#        run: |
#          make lint

      - name: Run unit test and get test coverage
        run: |
          make cover

      - name: Collect Test Coverage File
        uses: ncruces/go-coverage-report@v0.3.0
        with:
          coverage-file: _output/coverage.out
          report: 'true'
          amend: 'true'
          reuse-go: 'true'
        if: |
          matrix.go-version == '1.23.x'
        continue-on-error: true
#      - name: Collect Test Coverage File
#        uses: actions/upload-artifact@v4
#        with:
#          name: main-output
#          path: _output/coverage.out
#        if: |
#          matrix.go-version == '1.23.x'