name: lint and Test

on: [push, pull_request]

jobs:
  lint_and_test:
    name: Lint and Test - ${{ matrix.go-version }}
    strategy:
      matrix:
        go-version: [1.22.x, 1.23.x,1.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: false

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          make tools

      - name: Check copyright
        run: |
          make verify-copyright

      - name: Check syntax and styling of go sources
        run: |
          make lint

      - name: Run unit test and get test coverage
        run: |
          make cover

      - name: Collect Test Coverage File
        uses: actions/upload-artifact@v4
        with:
          name: main-output
          path: _output/coverage.out